name: AWS Lambda Deploy 
on:
  push:
    branches:
      - main
    paths:
      - 'go/**'

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: AWS set Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
      - run: aws sts get-caller-identity

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Lambda update function configuration
        run: |
          aws lambda update-function-configuration --function-name url-shortener-prod-lambda \
            --environment "Variables={ \
              APP_URL=${{ secrets.APP_URL }}, \
              BUCKET_NAME=${{ secrets.BUCKET_NAME }}, \
            }"
        
      - name: Lambda update function
        run: |
          cd go && GOOS=linux go build -o main main.go
          zip -r function.zip ./main
          aws lambda update-function-code --function-name url-shortener-prod-lambda --zip-file fileb://function.zip --publish